server:
  log_level: info

metrics:
  wal_directory: '/var/lib/grafana-agent'
  global:
    scrape_interval: 30s
    external_labels:
      hostname: ${HOSTNAME}
    remote_write:
      # Monitor-Service endpoint and port. Shared by Carbonara
      - url: http://${REMOTE-ENDPOINT}:${REMOTE-PORT}/api/v1/write
        basic_auth:
          # Basic auth username. Shared by Carbonara
          username: ${AUTH-UNAME}
          # Basic auth password. Shared by Carbonara
          password: ${AUTH-PWD}
        headers:
          tenant_id: ${AUTH-UNAME}
        queue_config:
          # Number of samples to buffer per shard before the client starts dropping them
          capacity: 10000
          # Maximum number of concurrent shards sending samples to the endpoint
          max_shards: 10
          # Minimum amount of concurrent shards sending samples to the endpoint
          min_shards: 1
          # Maximum number of samples per send
          max_samples_per_send: 500
          # Initial retry delay. The backoff time gets doubled for each retry
          min_backoff: 1s
          # Maximum retry delay
          max_backoff: 15s
  configs:
    - name: node-agent
      scrape_configs:
        - job_name: 'node-exporter'
          metrics_path: /metrics
          honor_labels: true
          honor_timestamps: false
          static_configs:
            # node_exporter localhost port
            - targets: ['localhost:9100']
              labels:
                instance: '${INSTANCE}'
                provider: '${AUTH-UNAME}'
    - name: ipmi-agent
      scrape_configs:
        - job_name: 'ipmi-exporter'
          metrics_path: /metrics
          honor_labels: true
          honor_timestamps: false
          static_configs:
            # ipmi_exporter localhost port
            - targets: ['localhost:9290']
              labels:
                instance: '${INSTANCE}'
                provider: '${AUTH-UNAME}'
    - name: scaph-agent
      scrape_configs:
        - job_name: 'scaph-power-exporter'
          metrics_path: /metrics
          honor_labels: true
          honor_timestamps: false
          static_configs:
            # scaph_rapl_exporter localhost port
            - targets: ['localhost:8080']
              labels:
                instance: '${INSTANCE}'
                provider: '${AUTH-UNAME}'
    - name: process-agent
      scrape_configs:
        - job_name: 'process-exporter'
          metrics_path: /metrics
          honor_labels: true
          honor_timestamps: false
          static_configs:
            # process_exporter localhost port
            - targets: ['localhost:9256']
              labels:
                instance: '${INSTANCE}'
                provider: '${AUTH-UNAME}'

integrations:
  agent:
    enabled: true
