- name: Install required system packages
  apt: name=python3-docker state=latest update_cache=yes

- name: Run cadvisor container
  community.docker.docker_container:
    name: cadvisor
    image: gcr.io/cadvisor/cadvisor:{{ cadvisor_version }}
    ports:
      - "8080:8080"
    privileged: true
    detach: yes
    devices:
      - "/dev/kmsg"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
