- name: add docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker repository to apt
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: install docker
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Restart and enable docker
  service:
    name: docker
    state: restarted
    enabled: yes

- name: Install required system packages
  apt: name=python3-docker state=latest update_cache=yes

- name: Run cadvisor container
  community.docker.docker_container:
    name: cadvisor
    image: gcr.io/cadvisor/cadvisor:{{ cadvisor_version }}
    ports:
      - "8080:8080"
    privileged: true
    detach: yes
    devices:
      - "/dev/kmsg"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
