- name: Check if node-exporter port is listening
  shell: netstat -tunlp | grep ":{{ nvalue }} " | sed -e 's/.*\///'
  register: node_port_check
  ignore_errors: true

- name: Print node-exporter port status
  debug:
    msg: "Node Exporter Port ... {{ 'Not In Use' if node_port_check.failed == true else 'In Use' }}"

- name: Check if ipmi-exporter port is listening
  shell: netstat -tunlp | grep ":{{ ivalue }} " | sed -e 's/.*\///'
  register: ipmi_port_check
  ignore_errors: true

- name: Print ipmi-exporter port status
  debug:
    msg: "IPMI Exporter Port ... {{ 'Not In Use' if ipmi_port_check.failed == true else 'In Use' }}"

- name: Check if dcgm-exporter port is listening
  shell: netstat -tunlp | grep ":{{ dvalue }} " | sed -e 's/.*\///'
  register: dcgm_port_check
  ignore_errors: true
  when: gvalue == true

- name: Print dcgm-exporter port status
  debug:
    msg: "DCGM Exporter Port ... {{ 'Not In Use' if dcgm_port_check.failed == true else 'In Use' }}"
  when: gvalue == true

- name: Check if smi-gpu-exporter port is listening
  shell: netstat -tunlp | grep ":{{ svalue }} " | sed -e 's/.*\///'
  register: smi_gpu_port_check
  ignore_errors: true
  when: gvalue == true

- name: Print smi-gpu-exporter port status
  debug:
    msg: "SMI GPU Exporter Port ... {{ 'Not In Use' if smi_gpu_port_check.failed == true else 'In Use' }}"
  when: gvalue == true