- name: Load IPMI kernel modules
  shell: |
    modprobe ipmi_devintf || true && modprobe ipmi_si || true

- name: Check if IPMI is available
  stat:
    path: /dev/ipmi0
  register: ipmi_check
  ignore_errors: true

- name: Install FreeIPMI tool suite
  apt:
    name: freeipmi-tools
    state: present
    update_cache: yes
    cache_valid_time: 3600
    install_recommends: no
  when: ipmi_check.stat.exists

- name: Download and extract IPMI Exporter
  shell: |
    curl -fsSL https://github.com/prometheus-community/ipmi_exporter/releases/download/v1.6.1/ipmi_exporter-1.6.1.linux-amd64.tar.gz |
    tar -zxvf - -C /usr/local/bin --strip-components=1 ipmi_exporter-1.6.1.linux-amd64/ipmi_exporter
    chown root:root /usr/local/bin/ipmi_exporter
  when: ipmi_check.stat.exists

- name: Back up existing ipmi_exporter.service
  shell: cp /etc/systemd/system/ipmi_exporter.service /etc/systemd/system/ipmi_exporter.service.backup
  args:
    creates: /etc/systemd/system/ipmi_exporter.service.backup
  ignore_errors: true
  when: ipmi_check.stat.exists and ansible.file.exists("/etc/systemd/system/ipmi_exporter.service")

- name: Back up existing ipmi_exporter sysconfig
  shell: cp /etc/sysconfig/ipmi_exporter /etc/sysconfig/ipmi_exporter.backup
  args:
    creates: /etc/sysconfig/ipmi_exporter.backup
  ignore_errors: true
  when: ipmi_check.stat.exists and ansible.file.exists("/etc/sysconfig/ipmi_exporter")

- name: Copy ipmi_exporter.service
  get_url:
    url: https://raw.githubusercontent.com/TryCarbonara/NodeInstallation/main/client/ipmi-exporter/ipmi_exporter.service
    dest: /etc/systemd/system/ipmi_exporter.service
    owner: root
    group: root
    mode: '0644'
  when: ipmi_check.stat.exists

- name: Create ipmi_exporter sysconfig
  copy:
    content: 'OPTIONS="--config.file=/carbonara/ipmi_local.yml --web.listen-address=:{{ ivalue }}"'
    dest: /etc/sysconfig/ipmi_exporter
    mode: '0644'
  when: ipmi_check.stat.exists

- name: Download ipmi_local.yml
  get_url:
    url: https://raw.githubusercontent.com/TryCarbonara/NodeInstallation/main/ipmi_local.yml
    dest: /carbonara/ipmi_local.yml
    owner: root
    group: root
    mode: '0644'
  when: ipmi_check.stat.exists

- name: Reload systemd
  systemd:
    daemon_reload: yes
  when: ipmi_check.stat.exists

- name: Restart and enable ipmi_exporter
  service:
    name: ipmi_exporter
    state: restarted
    enabled: yes
  when: ipmi_check.stat.exists

- name: Enable RAPL module if IPMI is not available
  shell: modprobe intel_rapl_common || true
  when: not ipmi_check.stat.exists
